# Generated by Django 3.2.9 on 2021-11-13 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(default='', verbose_name='Текст')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('condition', models.IntegerField(choices=[(0, 'Активно'), (1, 'Отложено'), (2, 'Выполнено')], default=0, verbose_name='Статус состояния')),
                ('mark', models.BooleanField(default=False, verbose_name='Публичная')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
